@if($admin->profile && $admin->profile->gender == 2)
    <p dir="RTL" style="margin-left:0in; margin-right:0in; text-align:right"><span style="font-size:11pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="font-size:14.0pt"><span style="font-family:&quot;B Nazanin&quot;">سرکار خانم {{$admin->last_name}}</span></span></span></span></p>
@elseif($admin->profile && $admin->profile->gender == 1)
    <p dir="RTL" style="margin-left:0in; margin-right:0in; text-align:right"><span style="font-size:11pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="font-size:14.0pt"><span style="font-family:&quot;B Nazanin&quot;">جناب آقای {{$admin->last_name}}</span></span></span></span></p>
@endif
<p dir="RTL" style="margin-left:0in; margin-right:0in; text-align:right"><span style="font-size:11pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="font-size:14.0pt"><span style="font-family:&quot;B Nazanin&quot;">با سلام و احترام</span></span></span></span></p>

<p dir="RTL" style="margin-left:0in; margin-right:0in; text-align:right"><span style="font-size:11pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="font-size:14.0pt"><span style="font-family:&quot;B Nazanin&quot;">آگهی &laquo;{{$job->title}}&raquo;  شرکت «{{$job->company->name}}» در حال منقضی شدن می باشد، لطفا با کلیک روی یکی از لینک های زیر وضعیت آگهی را مشخص فرمایید:</span></span></span></span></p>
<p dir="RTL" style="margin-left:0.5in; margin-right:0in; text-align:right"><span style="font-size:11pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="font-size:14.0pt"><span style="font-family:Symbol">&middot; </span></span><a href="{{route('jobs.extend',$job->id)}}" style="color:#0563c1; text-decoration:underline"><span style="font-size:14.0pt"><span style="font-family:&quot;B Nazanin&quot;"> تمدید آگهی به مدت ده روز</span></span></a></span></span></p>
<p dir="RTL" style="margin-left:0.5in; margin-right:0in; text-align:right"><span style="font-size:11pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="font-size:14.0pt"><span style="font-family:Symbol">&middot; </span></span><a href="{{route('jobs.show-non-automatic-extend',$job->id)}}" style="color:#0563c1; text-decoration:underline"><span style="font-size:14.0pt"><span style="font-family:&quot;B Nazanin&quot;"> تمدید آگهی به مدت دلخواه</span></span></a></span></span></p>

<p dir="RTL" style="margin-left:0.5in; margin-right:0in; text-align:right"><span style="font-size:11pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="font-size:14.0pt"><span style="font-family:Symbol">&middot; </span></span><a href="{{route('jobs.archive',$job->id)}}" style="color:#0563c1; text-decoration:underline"><span style="font-size:14.0pt"><span style="font-family:&quot;B Nazanin&quot;">بستن آگهی</span></span></a></span></span></p>
<p dir="RTL" style="margin-left:0in; margin-right:0in; text-align:right"><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="font-size:14.0pt"><span style="font-family:Symbol"><span style="color:red">&middot; </span></span></span><span style="font-size:14.0pt"><span style="font-family:&quot;B Nazanin&quot;">در صورتی که روی هیچ کدام از لینک ها کلیک نکنید، آگهی به صورت خودکار از روی سایت حذف خواهد شد.</span></span></span></span></p>
<p dir="RTL" style="margin-left:0in; margin-right:0in; text-align:right">&nbsp;</p>
<p dir="RTL" style="margin-left:0in; margin-right:0in; text-align:right"><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="font-size:14.0pt"><span style="font-family:&quot;B Nazanin&quot;">با تشکر</span></span></span></span></p>
<p dir="RTL" style="margin-left:0in; margin-right:0in; text-align:right"><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="font-size:14.0pt"><span style="font-family:&quot;B Nazanin&quot;">سامانه منابع انسانی گروه صنعتی گلرنگ</span></span></span></span></p>
